name: ChatOps Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print bash version
        run: bash --version
      - name: Print payload
        run: echo "${{toJSON(github.event)}}"
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.WRITE_TO_REPO_PERSONAL_ACCESS_TOKEN}}
          script: |
            commandToWorkflow = {"release":"release-command", "deploy": "deploy-command"}
            console.log(JSON.stringify(context.payload))
            if (!comment.startsWith("/")) {
              console.log("Commands need to start with '/'");
            }
            lookupKey = comment.substring(1); // cut first '/'
            event_type = commandToWorkflow[lookupKey];
            console.log(event_type);
        
            github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "release-command",
              client_payload: context.payload
            });
