name: comment
on:
  repository_dispatch:
    types: [release-command]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            payload = context.payload.client_payload

            console.log(JSON.stringify(payload))

            github.reactions.createForIssueComment({
              owner: payload.repository.owner.login,
              repo: payload.repository.name,
              comment_id: payload.comment.id,
              content: "rocket",
            });
