name: 'On Release'
on:
  release:
    types: [published]

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{github.event.tag_name}}
      - run: |
          echo $GITHUB_REF
          echo $GITHUB_SHA
