name: Release
on:
  issues:
    types:
      - labeled
jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.label.name == 'release' }}
    steps:
      - name: Setup Git Repo
        run: |
          git clone https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git .
          git config user.email "octocat@github.com"
          git config user.name ${GITHUB_ACTOR}
      - name: Bump version + Tag
        run: ./gradlew release -Prelease.useAutomaticVersion=true
      - name: Merge to master
        run: | 
          git checkout master
          git merge release
          git push origin master
