name: Release
on:
  issues:
    types:
      - labeled
jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.label.name == 'release' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("issue title", context.issue.title)
      - name: Set Git Author and remote
        run: |
          git config user.email "octocat@github.com"
          git config user.name "Octocat"
          echo $GITHUB_ACTOR
          echo ${GITHUB_ACTOR}
          git remote set-url origin "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
      - name: Create release branch
        run: git checkout -b release
      - name: Bump version + Tag
        run: ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{github.event.issue.title}}
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Merge to master
        run: | 
          git remote set-url origin "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch
          git merge release

