name: Release
on:
  issues:
    types:
      - labeled
jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.label.name == 'release' }}
    steps:
      - name: Install semver
        run: sudo apt-get install -y node-semver
      - name: Setup Git Repo
        run: |
          git clone https://${GITHUB_ACTOR}:${{secrets.WRITE_TO_REPO_PERSONAL_ACCESS_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git .
          git config user.email "octocat@github.com"
          git config user.name ${GITHUB_ACTOR}

      - name: Determine release version
        run: |
          version=`./gradlew properties -q | grep "^version:" | awk '{print $2}'`
          version_without_snapshot=${version%"-SNAPSHOT"}
          newversion=`semver -i major $version_without_snapshot`
          echo $newversion
          echo "::set-env name=NEW_VERSION::${newversion}"

      - name: Bump version + Tag
        env:
          NEW_VERSION: ${{env.NEW_VERSION}}
        run: ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=$NEW_VERSION
      - name: Merge to master
        run: |
          git checkout master
          git merge release
          git push master
      - name: Fail
        run: git bla
