name: Release
on:
  issues:
    types:
      - labeled
jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ startsWith( github.event.label.name, 'release:' )}}
    steps:
      - name: Install semver
        run: sudo apt-get install -y node-semver
      - name: Setup Git Repo
        run: |
          git clone https://${GITHUB_ACTOR}:${{secrets.WRITE_TO_REPO_PERSONAL_ACCESS_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git .
          git config user.email "octocat@github.com"
          git config user.name ${GITHUB_ACTOR}
      - uses: actions/github-script@0.9.0
        id: determine-bump-level
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prefix = "release:"
                    
            if (context.payload.issue.labels.length > 1) {
              await github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: 'Please add only one label'
              })
              throw new Error("More than one label provided")
            }
            const increment_level = context.payload.issue.labels.find(label => label.name.startsWith(prefix) )
            if (!increment_level) {
              await github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: 'Please add a bump Version'
              })
              throw new Error("Missing bump Version")
            }
            const bump_level = increment_level.name.substr(prefix.length)
            console.log(`::set-output name=bump_level::${bump_level}`)
      - name: Determine release version
        env:
          BUMP_LEVEL: ${{ steps.determine-bump-level.outputs.bump_level }}
        run: |
          version=`./gradlew properties -q | grep "^version:" | awk '{print $2}'`
          newversion=`semver -i $BUMP_LEVEL $version`
          
          echo "New $BUMP_LEVEL release - Current version: $version New version: $newversion"
          echo "::set-env name=NEW_VERSION::${newversion}"

      - name: Bump version + Tag
        env:
          NEW_VERSION: ${{env.NEW_VERSION}}
        run: ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=$NEW_VERSION
      - name: Merge to master
        run: |
          git checkout master
          git merge release
          git push origin master

      - uses: actions/github-script@0.9.0
        name: Comment Issue
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🎉 Deployment has been successful dispatched version ${process.env.NEW_VERSION}! 🚀`
            })
            await github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed"
            });
