name: Release
on:
  issues:
    types:
      - labeled
jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.label.name == 'release' }}
    steps:
      - name: Setup Git Repo
        run: |
          git clone https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git .
          git config user.email "octocat@github.com"
          git config user.name ${GITHUB_ACTOR}
          git checkout -b develop_new_snapshot
      - name: Bump version + Tag
        run: ./gradlew release -Prelease.useAutomaticVersion=true
      - name: Create Pull-Requests
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const master_pr = github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Release to master",
              head: "release",
              base: "master",
            })
            const develop_pr = github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Release to develop",
              head: "develop_new_snapshot",
              base: "develop",
            })
            const [master_pr_result, develop_pr_result] = await Promise.all([master_pr, develop_pr])
