name: Release
on:
  issues:
    types:
      - labeled
jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.label.name == 'release' }}
    steps:
      - name: Setup Git Repo
        run: |
          git clone https://${GITHUB_ACTOR}:${{secrets.WRITE_TO_REPO_PERSONAL_ACCESS_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git .
          git config user.email "octocat@github.com"
          git config user.name ${GITHUB_ACTOR}
          git checkout -b develop_new_snapshot
      - name: Read current version
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            cat gradle.properties
      - name: Bump version + Tag
        run: ./gradlew release -Prelease.useAutomaticVersion=true
      - name: Merge to master
        run: |
          git checkout master
          git merge release
          git push master
      - name: Fail
        run: git bla